language: go
before_install:
- mkdir lpsolve
- curl -L https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.0/lp_solve_5.5.2.0_dev_ux64.tar.gz | tar xvz -C lpsolve
go:
- 1.7
- 1.8
- tip
notifications:
  email: false
